---
abstract: 'Migrations for small home projects'
author:
  - 'Viacheslav Tykhanovskyi, C<viacheslav.t@gmail.com>'
build_requires:
  Test::Fatal: '0'
  Test::More: '0.98'
  Test::TempDir::Tiny: '0'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142690'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-mimi
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::mimi:
    file: lib/App/mimi.pm
    version: '0.01'
  App::mimi::db:
    file: lib/App/mimi/db.pm
requires:
  DBD::SQLite: '0'
  DBI: '0'
  Docopt: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/vti/app-mimi/issues
  homepage: https://github.com/vti/app-mimi
  repository: git://github.com/vti/app-mimi.git
version: '0.01'
x_authority: cpan:VTI
